# catppuccin cyan color is great
format = "$elixir$rust$c$package[\\[$directory\b\\]─$nix_shell─ $git_status$character](cyan)"

add_newline = false


[battery]
# it takes too long to load each time
disabled = true

[line_break]
disabled = true

[directory]
style = "bold"

[git_status]
format = "(\b[\\[$all_status$ahead_behind\\]]($style))"

[character]
success_symbol = "[─](cyan)"
error_symbol = "[─](red)"

[package]
format = "[$symbol$version]($style) "

[elixir]
format = "[$symbol]($style)"

[rust]
format = "[$symbol]($style)"

[c]
# available after 1.10 (pull #3631)
# fedora version is TOO LOW, and performance is BAD
format = "[$symbol]($style)"
symbol = " "

[nix_shell]
format = "[$symbol$state]($style)"
