name: "buildiso"
on:
  push:
    tags:
      - 'iso-v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Get Files
      run: |
        curl -O https://github.com/dongdigua/dongdigua.github.io/raw/main/org/internet_collections.org
        curl https://people.centos.org/areguera/backgrounds/c9/default/standard/hue-0.png -o centos9-motif.png

    - name: Fallback Patch
      run: |
        ./fallbacks/rofi.sh
        ./fallbacks/vim.sh
        ./fallbacks/emacs.sh
        ./fallbacks/sway.sh
        patch -p0 -F 10 < fallbacks/waybar.patch waybar/config

    - name: Build ISO
      run: |
        nix run github:nix-community/nixos-generators -- -f iso -c configuration.nix -o output

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "output/iso/nixos.iso"
